from typing import Protocol

from auto_cast.types import Batch, EncodedBatch, RolloutOutput, Tensor


class EncoderInterface(Protocol):
    """Encoder Interface."""

    def encode(self, batch: Batch) -> Tensor: ...
    def __call__(self, batch: Batch) -> Tensor: ...


class ProcessorInterface(Protocol):
    """Processor Interface."""

    def map(self, x: Tensor) -> Tensor: ...
    def rollout(self, batch: EncodedBatch) -> RolloutOutput: ...
    def __call__(self, batch: EncodedBatch) -> Tensor: ...


class DecoderInterface(Protocol):
    """Decoder Interface."""

    def decode(self, x: Tensor) -> Tensor: ...
    def __call__(self, batch: Batch) -> Tensor: ...


class EncoderDecoderInterface(Protocol):
    """Encoder-Decoder Interface."""

    def encode(self, batch: Batch) -> Tensor: ...
    def decode(self, x: Tensor) -> Tensor: ...
    def encode_decode(self, x: Batch) -> Tensor: ...
    def __call__(self, batch: Batch) -> Tensor: ...


class EncoderProcessorDecoderInterface(Protocol):
    """Encoder-Decoder Interface."""

    def encode(self, batch: Batch) -> Tensor: ...
    def decode(self, x: Tensor) -> Tensor: ...
    def map(self, x: EncodedBatch) -> Tensor: ...
    def encode_decode(self, x: Batch) -> Tensor: ...
    def rollout(self, batch: Batch) -> RolloutOutput: ...
    def __call__(self, batch: Batch) -> Tensor: ...
