# Encodes (128 x 128 x C_in) to (16 x 16 x 8), corresponding
# to compression rate of 24x for CNS (C_in = 3). This matches
# the latent space for the 64x64 encoders.
#
# This is approx 25M params (50M for the full autoencoder)

defaults:
  - dc_large

out_channels: 8
hid_channels: [64, 128, 256, 512]
hid_blocks: [3, 3, 3, 3]
