defaults:
  - /backbone@backbone: vit_small
  - _self_

_target_: autocast.processors.flow_matching_masked_window.FlowMatchingMaskedWindowProcessor
flow_ode_steps: 20
n_steps_input: auto
n_steps_output: auto
n_channels_out: auto
lmbda: 1.0
rho: 1.0
atleast: 1
