_target_: autocast.data.datamodule.SpatioTemporalDataModule
data_path: "${oc.env:AUTOCAST_DATASETS,./datasets}/gpe_high_complexity_9bd3865"
batch_size: 16
n_steps_input: 1
n_steps_output: 4
stride: 1
verbose: false
use_normalization: false
normalization_stats:
  # TODO
  stats:
    mean:
      density: 0.0
      phase: 0.0
    std:
      density: 1.0
      phase: 1.0
    mean_delta:
      density: 0.0
      phase: 0.0
    std_delta:
      density: 1.0
      phase: 1.0
  core_field_names: ["density", "phase"]
  constant_field_names: []
num_workers: 0
