_target_: autocast.data.datamodule.SpatioTemporalDataModule
data_path: "${oc.env:AUTOCAST_DATASETS,./datasets}/swe_crps_deterministic_32_128f_spinup5"
batch_size: 32
n_steps_input: 1
n_steps_output: 1
stride: 1
verbose: false
use_normalization: true
normalization_path: ${.data_path}/stats.yml
num_workers: 0
