# @package _global_
defaults:
  - /distributed: single_gpu_slurm
  - override /datamodule: 128x128/gpe_laser_only_wake
  - override /encoder@model.encoder: 128x128/dc_cout8
  - override /decoder@model.decoder: 128x128/dc_cout8
  - _self_

experiment_name: cache_latents_gpe_128

datamodule:
  use_normalization: true
  batch_size: 4

model:
  encoder:
    periodic: false
    pixel_shuffle: true
  decoder:
    periodic: false
    pixel_shuffle: true
