# @package _global_
defaults:
  - /distributed: single_gpu_slurm
  - override /datamodule: 128x128/gray_scott
  - override /encoder@model.encoder: dc_f8c8
  - override /decoder@model.decoder: dc_f8c8
  - _self_

experiment_name: cache_latents_gs_128

datamodule:
  use_normalization: true
  batch_size: 4

model:
  encoder:
    periodic: true
    pixel_shuffle: true
  decoder:
    periodic: true
    pixel_shuffle: true
