# @package _global_
defaults:
  - override /hydra/launcher: slurm
  - _self_

devices_per_node: 4
num_nodes: 1

trainer:
  max_time: "00:12:00:00"
  accelerator: gpu
  strategy: ddp
  devices: ${devices_per_node}
  num_nodes: ${num_nodes}

eval:
  accelerator: auto
  strategy: ddp
  devices: ${devices_per_node}
  num_nodes: ${num_nodes}

hydra:
  launcher:
    nodes: ${num_nodes}
    gpus_per_node: ${devices_per_node}
    tasks_per_node: ${devices_per_node}
    additional_parameters:
      # Since each process is bound to a GPU, avoid requesting CPU memory per GPU.
      mem: 0
