# @package _global_
defaults:
  - override /hydra/launcher: slurm
  - _self_

trainer:
  max_time: "00:12:00:00"
  accelerator: gpu
  devices: 4
  strategy: ddp
  num_nodes: 1

hydra:
  launcher:
    gpus_per_node: 4
    tasks_per_node: 4
